services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - task_management

  test_db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "${TEST_DB_PORT}:5432"
    networks:
      - task_management

  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - task_management
    command: sh -c "make db.migrate && make run"
    volumes:
      - .:/app
    depends_on:
      - db

networks:
  task_management:
